schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/Benau/go_rlottie"]
    version = "v0.0.0-20210807002906-98c1b2421989"
    hash = "sha256-oIe5oARFioEFTv/tR8V0PJGvsW1qB0/ZFo7E/UPhJX4="
  [mod."github.com/PaulSonOfLars/gotgbot/v2"]
    version = "v2.0.0-rc.33"
    hash = "sha256-9rZxcLi/+e0EAEmAon9S+Uo87m31PURyZrMyJIWrlVE="
  [mod."github.com/av-elier/go-decimal-to-rational"]
    version = "v0.0.0-20250603203441-f39a07f43ff3"
    hash = "sha256-yloaXnQFtjlXwn7vhKkJpqXga6PWRLWeaV8fYdcngeo="
  [mod."github.com/emersion/go-vcard"]
    version = "v0.0.0-20241024213814-c9703dde27ff"
    hash = "sha256-FY3jy4rGASVbssqoAsaV9XqUWBaWWKRwNEJVIkx120g="
  [mod."github.com/forPelevin/gomoji"]
    version = "v1.3.1"
    hash = "sha256-nXMcMbCS9MjVUNE/Pasg4W3HhzPVdoyLGQn1lbtX7iU="
  [mod."github.com/go-co-op/gocron"]
    version = "v1.37.0"
    hash = "sha256-/EAcgc/GzQP88CcvLwwi5HV01bZM7bezPfWRGRLHRTY="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.9.3"
    hash = "sha256-37CNj7G2S20w98rVAyFiScHQ5uXI/NSYY6Gsl41UwgY="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.5"
    hash = "sha256-+bzuXlJnsvNEGjuhHIiZwmWepEmwj3Fl1ktLD50IKlU="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/jinzhu/now"]
    version = "v1.1.5"
    hash = "sha256-NNLqoFx9FczBBDpD0O0aSHnC/YDZ9E/xQ340o7u63IM="
  [mod."github.com/kettek/apng"]
    version = "v0.0.0-20220823221153-ff692776a607"
    hash = "sha256-VuxcQDPJsmSpueFu9ECqG/EIr29eDALA1iRpl2pquzI="
  [mod."github.com/lithammer/fuzzysearch"]
    version = "v1.1.8"
    hash = "sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.14"
    hash = "sha256-JC60PjKj7MvhZmUHTZ9p372FV72I9Mxvli3fivTbxuA="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.28"
    hash = "sha256-mskU1xki6J1Fj6ItNgY/XNetB4Ta4jufEr4+JvTd7qs="
  [mod."github.com/mdp/qrterminal/v3"]
    version = "v3.2.1"
    hash = "sha256-OqRnO3cSJfMZwOivLgWw0bozmUMaoPVsm/8R/GwyBh0="
  [mod."github.com/petermattis/goid"]
    version = "v0.0.0-20250508124226-395b08cebbdb"
    hash = "sha256-hkQc+2SSFMQs73aBkaHSHh7WV8oTNkFDTlvyJHZgDjE="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/robfig/cron/v3"]
    version = "v3.0.1"
    hash = "sha256-FUdqNbWYi5biQc/tjCeqzxu4iy4ot1ZvDU1M1wRf/6k="
  [mod."github.com/rs/zerolog"]
    version = "v1.34.0"
    hash = "sha256-M503WwzPvqbOas3f70FQNXoWG17eV/XU6FubtB6P0uo="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/watgbridge/tgsconverter"]
    version = "v0.0.0-20240710075117-d1c05581b842"
    hash = "sha256-0S477WzYnjZNofoxiuYMR0Wc/elXu74WDUi7N8QoK0Q="
  [mod."github.com/watgbridge/webp"]
    version = "v0.0.0-20240709143015-99fb5316f772"
    hash = "sha256-CL7WYufOA7rxy8Tn/B8iVYa/Cf7JdIGEko2XGYoF2Fo="
  [mod."go.mau.fi/libsignal"]
    version = "v0.2.0"
    hash = "sha256-GbXdMQGSwDlSaVvrnueHSstiWeoo3qjyZu/J7IntzOo="
  [mod."go.mau.fi/util"]
    version = "v0.8.8"
    hash = "sha256-NHZwK+dAiAKjL0xexHulTo4S/OvUKME5WNhhWRYT6as="
  [mod."go.mau.fi/whatsmeow"]
    version = "v0.0.0-20250708133942-938c7dd5dc51"
    hash = "sha256-MrpXXijg4kqRBeNbEWwQ0xCyUTY3qeRCP5Ab5sxLGv8="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/crypto"]
    version = "v0.39.0"
    hash = "sha256-FtwjbVoAhZkx7F2hmzi9Y0J87CVVhWcrZzun+zWQLzc="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250620022241-b7579e27df2b"
    hash = "sha256-IsDTeuWLj4UkPO4NhWTvFeZ22WNtlxjoWiyAJh6zdig="
  [mod."golang.org/x/net"]
    version = "v0.41.0"
    hash = "sha256-6/pi8rNmGvBFzkJQXkXkMfL1Bjydhg3BgAMYDyQ/Uvg="
  [mod."golang.org/x/sync"]
    version = "v0.15.0"
    hash = "sha256-Jf4ehm8H8YAWY6mM151RI5CbG7JcOFtmN0AZx4bE3UE="
  [mod."golang.org/x/sys"]
    version = "v0.33.0"
    hash = "sha256-wlOzIOUgAiGAtdzhW/KPl/yUVSH/lvFZfs5XOuJ9LOQ="
  [mod."golang.org/x/term"]
    version = "v0.32.0"
    hash = "sha256-4cM/vhb8EUrlfHidBRfjYEQlUQehXiydJN77YkQvAic="
  [mod."golang.org/x/text"]
    version = "v0.26.0"
    hash = "sha256-N+27nBCyGvje0yCTlUzZoVZ0LRxx4AJ+eBlrFQVRlFQ="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.6"
    hash = "sha256-lT5qnefI5FDJnowz9PEkAGylH3+fE+A3DJDkAyy9RMc="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gorm.io/driver/mysql"]
    version = "v1.6.0"
    hash = "sha256-F+evQbMZ5NPVw5u5wHiie5Gz90OwlNBQLHleMdQQoeo="
  [mod."gorm.io/driver/postgres"]
    version = "v1.6.0"
    hash = "sha256-j5ExpGS3aiO0fcMKSFJO/BkLFglzzo3Pt2Yj+rCf5PQ="
  [mod."gorm.io/driver/sqlite"]
    version = "v1.6.0"
    hash = "sha256-IrSl870ciJyDj0Pdx189JG+sN+Sli3ylfR+JJt/dWgc="
  [mod."gorm.io/gorm"]
    version = "v1.30.0"
    hash = "sha256-2TXzjY7fCjDwAfkKyTE3Dat+6lSdw8biKLREM92Ygbs="
  [mod."rsc.io/qr"]
    version = "v0.2.0"
    hash = "sha256-I3fAJwwZhIrgBbCjWvIElAE9JqG2y59KRBc78EYi3RM="
