#[Service]
#Environment=HTTPS_PROXY=socks5://127.0.0.1:1180
#Environment=NO_PROXY=localhost,127.0.0.1,::1

# Go’s default net/http transport automatically reads HTTP_PROXY, HTTPS_PROXY, and NO_PROXY.
# Telegram client uses http.Client{}
# sudo mkdir -p /etc/systemd/system/watgbridge.service.d/
# sudo cp proxy.conf /etc/systemd/system/watgbridge.service.d/
